Модель и CRUD для телеграм каналов
Studio-Yandex-Practicum/telestat_bot_team_4 pull request #6
Opened 2024-05-07 21:49 UTC by sof07

-  Добавлена модель и CRUD для тг каналов
- Текст перенесен в модули
- Добавлен хендлер который добавляет ТГ канал в БД, когда в канал добавляют бот

2024-05-07 22:38 UTC, Devayter requested changes

2024-05-07 22:38 UTC, Devayter commented on app/handlers/handlers.py
> +@router.my_chat_member(
Это вообще рабочий код, ты его как-то проверял? Просто я не нашел в свое время возможности отслеживать назначение Админом и думал, что мы решили добавлять группы в ручную. Если это решение правильное, то отлично, но тогда нужно убрать MEMBER и оставить только Админа, потому что группа у нас будет сейчас создаваться 2 раза, когда добавляют бота и когда его делают админом

2024-05-07 22:38 UTC, Devayter commented on app/crud/groups.py
> +        is_choosed: bool,
is_choosed лишнее, потому что у нас модель будет создаваться всегда с False, передавать для этого ничего не нужно

2024-05-07 22:38 UTC, Devayter commented on main.py
> +    # dp_management.include_router(test.router)
Не понимаю, что это и для чего тут нужно

2024-05-08 07:41 UTC, sof07 commented on app/handlers/handlers.py
> +@router.my_chat_member(
> Это вообще рабочий код, ты его как-то проверял? Просто я не нашел в свое время возможности отслеживать назначение Админом и думал, что мы решили добавлять группы в ручную. Если это решение правильное, то отлично, но тогда нужно убрать MEMBER и оставить только Админа, потому что группа у нас будет сейчас создаваться 2 раза, когда добавляют бота и когда его делают админом

Этот код отлавливает добавление в группу бота в ручную, смену статуса на админ не отлавливает. Как добавить бота сразу админом не нашел в телеге, оставил фильтр админ на случай, если все же можно как то сразу админом назначить. На мой взгляд нас устроит и простое добавление бота в канал, что бы собрать список каналов. А про дублирование групп да, я об этом подумал уже в кровати. Думаю в любом случае, перед добавлением надо проверять базу на наличие дубликатов.

2024-05-08 07:42 UTC, sof07 commented on main.py
> +    # dp_management.include_router(test.router)
> Не понимаю, что это и для чего тут нужно

Это осталось после тестирования :)

2024-05-09 20:36 UTC, sof07 commented on app/handlers/handlers.py
> +@router.my_chat_member(
Добавил проверку на дубликаты

2024-05-09 20:36 UTC, sof07 commented
Добавил alembic

2024-05-10 14:04 UTC, merged