Recording users in database
Studio-Yandex-Practicum/telestat_bot_team_4 pull request #8
Opened 2024-05-13 21:20 UTC by sof07

- сбор статистики по пользователям и добавление ее в базу, по команде начать сбор статистики
- определение пола по имени
- фильтр на админа, админов тянет из базы
- чуть подредактировал все CRUDы, иначе запустить  их не удалось

2024-05-13 22:43 UTC, Devayter requested changes
не нужно каждый раз создавать сессию, все необходимое мы уже сделали в db.py

- в файле с хендлерами мы импортируем from sqlalchemy.ext.asyncio import AsyncSession

- далее принимаем в самом хендлере сразу после message принимаем session: AsyncSession  и при вызове метода crud передаем туда эту сессию, должно работать

2024-05-14 05:29 UTC, sof07 commented
Должно, с этого и начал, но не работает, постоянно просит обязательный аргумент session, попробуй сам, может я криворукий. Пробовал через main передать, тоже не получается

2024-05-14 18:56 UTC, Devayter commented
можешь править, сейчас смержу ветку с middleware и сможешь принимать сессии

2024-05-14 21:01 UTC, sof07 commented
Исправил

2024-05-15 18:03 UTC, merged